name: fancy_toast_advance
description: An advanced fancy toast widget for Flutter with icons, colors, positions, and animations.
version: 1.0.3
homepage: https://github.com/Mohammad-Afzal786/fancy_toast_advance
repository: https://github.com/Mohammad-Afzal786/fancy_toast_advance
issue_tracker: https://github.com/Mohammad-Afzal786/fancy_toast_advance/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0